definitions:
  config:
    /hippo:namespaces/publishing/base:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: c56d57e6-0258-4981-9b3c-8c98c9468ba3
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: c316cde0-359f-4a0d-96bf-f59515c50af6
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 166bb92c-a714-4a47-8f23-ba458090b1e9
          hipposysedit:node: true
          hipposysedit:supertype: ['publishing:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.publishing.com/publishing/nt/1.0
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:title
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: publishing:base
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          publishing:summary: ''
          publishing:title: ''
          jcr:uuid: d5dc4b12-ecfd-4443-abf3-5c74b7861d63
          hippostdpubwf:lastModificationDate: 2019-09-03T14:51:07.551+01:00
          hippostdpubwf:creationDate: 2019-09-03T14:51:07.552+01:00
          /publishing:content:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            hint: Enter a title for this content item
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Summary
            field: summary
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: Enter a summary of this content item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            caption: Content
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: The main html content for this item.
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
