definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/article
            hst:relativecontentpath: ${1}
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/category
              hst:relativecontentpath: ${parent}/index
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/home
            hst:relativecontentpath: index
            hst:refId: root
          /sitemap.xml:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:components/sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-layout.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-footer.ftl
          /base-notifications:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-notifications.ftl
          /base-siteheader:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-siteheader.ftl
          /article-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/article-main.ftl
          /breadcrumbs:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/breadcrumbs.ftl
          /category-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/category-main.ftl
          /home-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/home-main.ftl
          /sitemap.ftl:
            jcr:primaryType: hst:template
            hst:script: '<#ftl attributes={"content_type": "application/xml"} />${sitemap}'
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
      /publishing:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /trading-nation:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
